# Generated by Django 4.2.7 on 2024-05-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Covid19', 'Covid19'), ('Heart Disease', 'Heart Disease'), ('Immunization', 'Immunization'), ('Mental Health', 'Mental Health')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='blog/')),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
